box(
  title = p("Life-Stage Domain and Variable Class",
            actionLink(inputId = "esvFields",
                       label = "",
                       icon = icon("question-circle"))),
  status = 'primary',
  solidHeader = TRUE,
  collapsible = TRUE,
  width = 12,
  shinyWidgets::checkboxGroupButtons('domainNodeList',
                                     'Life-Stage Domain',
                                     #choices = LSFDomainTibble$domainTitle,
                                     choiceNames = lsfDomains()$domainTitle,
                                     choiceValues = lsfDomains()$id,
                                     justified = F,
                                     status = 'default',
                                     size = 'sm',
                                     width = '100%',
                                     checkIcon = checkboxGroupButtonsIcons),
  uiOutput('esvPerDomain')
)